package com.cc.taskmanager.enums;

public enum ActionType {
	ADD_NEW_TASK,
	UPDATE_TASK_TITLE,
	UPDATE_TASK_DESCRIPTION,
	UPDATE_TASK_DUE_DATE,
	UPDATE_TASK_PRIORITY,
	UPDATE_TASK_STATUS,
	DELETE_TASK,
	UNDO_DELETE_TASK,
	UPDATE_TASK_TAGS

}
